// Permission resources that can be protected
export const PERMISSION_RESOURCES = {
  USER: 'user',
  SETTINGS: 'settings',
  ADMIN: 'admin',
  VIEW: 'view',
  // Add your microservice-specific resources here
  RESOURCE: 'resource',
  DATA: 'data',
} as const;

// Actions that can be performed on resources
export const PERMISSION_ACTIONS = {
  CREATE: 'create',
  READ: 'read',
  UPDATE: 'update',
  DELETE: 'delete',
  MANAGE: 'manage',
  ACCESS: 'access',
  APPROVE: 'approve',
  REJECT: 'reject',
  SUBMIT: 'submit',
  ACCESS_MAIN: 'access_main',
  ACCESS_TABLET: 'access_tablet',
  ACCESS_PARENT: 'access_parent',
} as const;

// Default permissions for each role
export const DEFAULT_ROLE_PERMISSIONS = {
  teacher: [
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_MAIN}`,
  ],
  assistant_director: [
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.DELETE}`,
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.APPROVE}`,
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.CREATE}`,
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_MAIN}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_TABLET}`,
  ],
  director: [
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.UPDATE}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_MAIN}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_TABLET}`,
  ],
  admin: [
    `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.SETTINGS}.${PERMISSION_ACTIONS.MANAGE}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_MAIN}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_TABLET}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_PARENT}`,
  ],
  superadmin: [
    `${PERMISSION_RESOURCES.ADMIN}.${PERMISSION_ACTIONS.MANAGE}`,
    // SuperAdmin has all permissions by default
  ],
  parent: [
    `${PERMISSION_RESOURCES.DATA}.${PERMISSION_ACTIONS.READ}`,
    `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_PARENT}`,
  ]
};

// System permission definitions
export const SYSTEM_PERMISSIONS = [
  {
    name: `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.CREATE}`,
    resource: PERMISSION_RESOURCES.RESOURCE,
    action: PERMISSION_ACTIONS.CREATE,
    description: 'Create new resources',
  },
  {
    name: `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.READ}`,
    resource: PERMISSION_RESOURCES.RESOURCE,
    action: PERMISSION_ACTIONS.READ,
    description: 'View resources',
  },
  {
    name: `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.UPDATE}`,
    resource: PERMISSION_RESOURCES.RESOURCE,
    action: PERMISSION_ACTIONS.UPDATE,
    description: 'Update existing resources',
  },
  {
    name: `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.DELETE}`,
    resource: PERMISSION_RESOURCES.RESOURCE,
    action: PERMISSION_ACTIONS.DELETE,
    description: 'Delete resources',
  },
  {
    name: `${PERMISSION_RESOURCES.RESOURCE}.${PERMISSION_ACTIONS.MANAGE}`,
    resource: PERMISSION_RESOURCES.RESOURCE,
    action: PERMISSION_ACTIONS.MANAGE,
    description: 'Full management of resources',
  },
  {
    name: `${PERMISSION_RESOURCES.USER}.${PERMISSION_ACTIONS.MANAGE}`,
    resource: PERMISSION_RESOURCES.USER,
    action: PERMISSION_ACTIONS.MANAGE,
    description: 'Manage users and roles',
  },
  {
    name: `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_MAIN}`,
    resource: PERMISSION_RESOURCES.VIEW,
    action: PERMISSION_ACTIONS.ACCESS_MAIN,
    description: 'Access main application view',
  },
  {
    name: `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_TABLET}`,
    resource: PERMISSION_RESOURCES.VIEW,
    action: PERMISSION_ACTIONS.ACCESS_TABLET,
    description: 'Access tablet view',
  },
  {
    name: `${PERMISSION_RESOURCES.VIEW}.${PERMISSION_ACTIONS.ACCESS_PARENT}`,
    resource: PERMISSION_RESOURCES.VIEW,
    action: PERMISSION_ACTIONS.ACCESS_PARENT,
    description: 'Access parent view',
  },
];